// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Profile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __Profile_h__
#define __Profile_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/BuiltinSequences.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace hat
{

class Profile;

}

}

namespace hat
{

class Profile;
bool operator==(const Profile&, const Profile&);
bool operator<(const Profile&, const Profile&);

}

namespace IceInternal
{

::Ice::Object* upCast(::hat::Profile*);
::IceProxy::Ice::Object* upCast(::IceProxy::hat::Profile*);

}

namespace hat
{

typedef ::IceInternal::Handle< ::hat::Profile> ProfilePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::hat::Profile> ProfilePrx;

void __read(::IceInternal::BasicStream*, ProfilePrx&);
void __patch__ProfilePtr(void*, ::Ice::ObjectPtr&);

}

namespace hat
{

class Callback_Profile_setHash_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Profile_setHash_Base> Callback_Profile_setHashPtr;

class Callback_Profile_getHash_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Profile_getHash_Base> Callback_Profile_getHashPtr;

}

namespace IceProxy
{

namespace hat
{

class Profile : virtual public ::IceProxy::Ice::Object
{
public:

    void setHash(const ::std::string& name, const ::std::string& hash)
    {
        setHash(name, hash, 0);
    }
    void setHash(const ::std::string& name, const ::std::string& hash, const ::Ice::Context& __ctx)
    {
        setHash(name, hash, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash)
    {
        return begin_setHash(name, hash, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash, const ::Ice::Context& __ctx)
    {
        return begin_setHash(name, hash, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setHash(name, hash, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setHash(name, hash, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash, const ::hat::Callback_Profile_setHashPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setHash(name, hash, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setHash(const ::std::string& name, const ::std::string& hash, const ::Ice::Context& __ctx, const ::hat::Callback_Profile_setHashPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setHash(name, hash, &__ctx, __del, __cookie);
    }

    void end_setHash(const ::Ice::AsyncResultPtr&);
    
private:

    void setHash(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setHash(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string getHash(const ::std::string& name)
    {
        return getHash(name, 0);
    }
    ::std::string getHash(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return getHash(name, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name)
    {
        return begin_getHash(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_getHash(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getHash(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getHash(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name, const ::hat::Callback_Profile_getHashPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getHash(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getHash(const ::std::string& name, const ::Ice::Context& __ctx, const ::hat::Callback_Profile_getHashPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getHash(name, &__ctx, __del, __cookie);
    }

    ::std::string end_getHash(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string getHash(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getHash(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Profile> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Profile> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Profile*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Profile*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace hat
{

class Profile : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void setHash(const ::std::string&, const ::std::string&, const ::Ice::Context*) = 0;

    virtual ::std::string getHash(const ::std::string&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace hat
{

class Profile : virtual public ::IceDelegate::hat::Profile,
                virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void setHash(const ::std::string&, const ::std::string&, const ::Ice::Context*);

    virtual ::std::string getHash(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace hat
{

class Profile : virtual public ::IceDelegate::hat::Profile,
                virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void setHash(const ::std::string&, const ::std::string&, const ::Ice::Context*);

    virtual ::std::string getHash(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace hat
{

class Profile : virtual public ::Ice::Object
{
public:

    typedef ProfilePrx ProxyType;
    typedef ProfilePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void setHash(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setHash(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string getHash(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getHash(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const Profile& l, const Profile& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Profile& l, const Profile& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace hat
{

template<class T>
class CallbackNC_Profile_setHash : public Callback_Profile_setHash_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Profile_setHash(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Profile_setHashPtr
newCallback_Profile_setHash(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_setHash<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Profile_setHashPtr
newCallback_Profile_setHash(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_setHash<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Profile_setHashPtr
newCallback_Profile_setHash(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_setHash<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Profile_setHashPtr
newCallback_Profile_setHash(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_setHash<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Profile_setHash : public Callback_Profile_setHash_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Profile_setHash(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Profile_setHashPtr
newCallback_Profile_setHash(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_setHash<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Profile_setHashPtr
newCallback_Profile_setHash(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_setHash<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Profile_setHashPtr
newCallback_Profile_setHash(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_setHash<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Profile_setHashPtr
newCallback_Profile_setHash(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_setHash<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Profile_getHash : public Callback_Profile_getHash_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_Profile_getHash(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::ProfilePrx __proxy = ::hat::ProfilePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getHash(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_Profile_getHashPtr
newCallback_Profile_getHash(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_getHash<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Profile_getHashPtr
newCallback_Profile_getHash(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Profile_getHash<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Profile_getHash : public Callback_Profile_getHash_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_Profile_getHash(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::ProfilePrx __proxy = ::hat::ProfilePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getHash(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Profile_getHashPtr
newCallback_Profile_getHash(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_getHash<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Profile_getHashPtr
newCallback_Profile_getHash(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Profile_getHash<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
