// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Profile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#include <Profile.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __hat__Profile__refreshPath_name = "refreshPath";

static const ::std::string __hat__Profile__updateFile_name = "updateFile";

static const ::std::string __hat__Profile__updateMeta_name = "updateMeta";

static const ::std::string __hat__Profile__updateFeature_name = "updateFeature";

::Ice::Object* IceInternal::upCast(::hat::Profile* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::hat::Profile* p) { return p; }

void
hat::__read(::IceInternal::BasicStream* __is, ::hat::ProfilePrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::hat::Profile;
        v->__copyFrom(proxy);
    }
}

void
hat::FileStat::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(id);
    __os->write(uri);
    __os->write(pathname);
    __os->write(stamp);
    __os->write(size);
}

void
hat::FileStat::__read(::IceInternal::BasicStream* __is)
{
    __is->read(id);
    __is->read(uri);
    __is->read(pathname);
    __is->read(stamp);
    __is->read(size);
}

void
hat::__writeFileStatSeq(::IceInternal::BasicStream* __os, const ::hat::FileStat* begin, const ::hat::FileStat* end)
{
    ::Ice::Int size = static_cast< ::Ice::Int>(end - begin);
    __os->writeSize(size);
    for(int i = 0; i < size; ++i)
    {
        begin[i].__write(__os);
    }
}

void
hat::__readFileStatSeq(::IceInternal::BasicStream* __is, ::hat::FileStatSeq& v)
{
    ::Ice::Int sz;
    __is->readAndCheckSeqSize(22, sz);
    v.resize(sz);
    for(int i = 0; i < sz; ++i)
    {
        v[i].__read(__is);
    }
}

void
hat::ImageMeta::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(id);
    __os->write(width);
    __os->write(height);
    __os->write(origin);
}

void
hat::ImageMeta::__read(::IceInternal::BasicStream* __is)
{
    __is->read(id);
    __is->read(width);
    __is->read(height);
    __is->read(origin);
}

void
hat::ImageFeature::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(id);
}

void
hat::ImageFeature::__read(::IceInternal::BasicStream* __is)
{
    __is->read(id);
}

::hat::FileStatSeq
IceProxy::hat::Profile::refreshPath(const ::std::string& path, const ::hat::FileStatSeq& fss, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__hat__Profile__refreshPath_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::hat::Profile* __del = dynamic_cast< ::IceDelegate::hat::Profile*>(__delBase.get());
            return __del->refreshPath(path, fss, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::hat::Profile::begin_refreshPath(const ::std::string& path, const ::hat::FileStatSeq& fss, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__hat__Profile__refreshPath_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __hat__Profile__refreshPath_name, __del, __cookie);
    try
    {
        __result->__prepare(__hat__Profile__refreshPath_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(path);
        if(fss.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            ::hat::__writeFileStatSeq(__os, &fss[0], &fss[0] + fss.size());
        }
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::hat::FileStatSeq
IceProxy::hat::Profile::end_refreshPath(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __hat__Profile__refreshPath_name);
    ::hat::FileStatSeq __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    ::hat::__readFileStatSeq(__is, __ret);
    __is->endReadEncaps();
    return __ret;
}

bool
IceProxy::hat::Profile::updateFile(const ::hat::FileStat& stat, const ::std::string& hash, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__hat__Profile__updateFile_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::hat::Profile* __del = dynamic_cast< ::IceDelegate::hat::Profile*>(__delBase.get());
            return __del->updateFile(stat, hash, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::hat::Profile::begin_updateFile(const ::hat::FileStat& stat, const ::std::string& hash, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__hat__Profile__updateFile_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __hat__Profile__updateFile_name, __del, __cookie);
    try
    {
        __result->__prepare(__hat__Profile__updateFile_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        stat.__write(__os);
        __os->write(hash);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::hat::Profile::end_updateFile(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __hat__Profile__updateFile_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

bool
IceProxy::hat::Profile::updateMeta(const ::hat::ImageMeta& meta, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__hat__Profile__updateMeta_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::hat::Profile* __del = dynamic_cast< ::IceDelegate::hat::Profile*>(__delBase.get());
            return __del->updateMeta(meta, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::hat::Profile::begin_updateMeta(const ::hat::ImageMeta& meta, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__hat__Profile__updateMeta_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __hat__Profile__updateMeta_name, __del, __cookie);
    try
    {
        __result->__prepare(__hat__Profile__updateMeta_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        meta.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::hat::Profile::end_updateMeta(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __hat__Profile__updateMeta_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

bool
IceProxy::hat::Profile::updateFeature(const ::hat::ImageFeature& feature, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__hat__Profile__updateFeature_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::hat::Profile* __del = dynamic_cast< ::IceDelegate::hat::Profile*>(__delBase.get());
            return __del->updateFeature(feature, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::hat::Profile::begin_updateFeature(const ::hat::ImageFeature& feature, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__hat__Profile__updateFeature_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __hat__Profile__updateFeature_name, __del, __cookie);
    try
    {
        __result->__prepare(__hat__Profile__updateFeature_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        feature.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::hat::Profile::end_updateFeature(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __hat__Profile__updateFeature_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::hat::Profile::ice_staticId()
{
    return ::hat::Profile::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::hat::Profile::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::hat::Profile);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::hat::Profile::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::hat::Profile);
}

::IceProxy::Ice::Object*
IceProxy::hat::Profile::__newInstance() const
{
    return new Profile;
}

::hat::FileStatSeq
IceDelegateM::hat::Profile::refreshPath(const ::std::string& path, const ::hat::FileStatSeq& fss, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __hat__Profile__refreshPath_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(path);
        if(fss.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            ::hat::__writeFileStatSeq(__os, &fss[0], &fss[0] + fss.size());
        }
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::hat::FileStatSeq __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        ::hat::__readFileStatSeq(__is, __ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::hat::Profile::updateFile(const ::hat::FileStat& stat, const ::std::string& hash, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __hat__Profile__updateFile_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        stat.__write(__os);
        __os->write(hash);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::hat::Profile::updateMeta(const ::hat::ImageMeta& meta, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __hat__Profile__updateMeta_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        meta.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::hat::Profile::updateFeature(const ::hat::ImageFeature& feature, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __hat__Profile__updateFeature_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        feature.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::hat::FileStatSeq
IceDelegateD::hat::Profile::refreshPath(const ::std::string& path, const ::hat::FileStatSeq& fss, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::hat::FileStatSeq& __result, const ::std::string& path, const ::hat::FileStatSeq& fss, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_path(path),
            _m_fss(fss)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::hat::Profile* servant = dynamic_cast< ::hat::Profile*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->refreshPath(_m_path, _m_fss, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::hat::FileStatSeq& _result;
        const ::std::string& _m_path;
        const ::hat::FileStatSeq& _m_fss;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __hat__Profile__refreshPath_name, ::Ice::Normal, __context);
    ::hat::FileStatSeq __result;
    try
    {
        _DirectI __direct(__result, path, fss, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::hat::Profile::updateFile(const ::hat::FileStat& stat, const ::std::string& hash, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::hat::FileStat& stat, const ::std::string& hash, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_stat(stat),
            _m_hash(hash)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::hat::Profile* servant = dynamic_cast< ::hat::Profile*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->updateFile(_m_stat, _m_hash, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::hat::FileStat& _m_stat;
        const ::std::string& _m_hash;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __hat__Profile__updateFile_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, stat, hash, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::hat::Profile::updateMeta(const ::hat::ImageMeta& meta, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::hat::ImageMeta& meta, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_meta(meta)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::hat::Profile* servant = dynamic_cast< ::hat::Profile*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->updateMeta(_m_meta, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::hat::ImageMeta& _m_meta;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __hat__Profile__updateMeta_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, meta, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::hat::Profile::updateFeature(const ::hat::ImageFeature& feature, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::hat::ImageFeature& feature, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_feature(feature)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::hat::Profile* servant = dynamic_cast< ::hat::Profile*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->updateFeature(_m_feature, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::hat::ImageFeature& _m_feature;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __hat__Profile__updateFeature_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, feature, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
hat::Profile::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __hat__Profile_ids[2] =
{
    "::Ice::Object",
    "::hat::Profile"
};

bool
hat::Profile::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__hat__Profile_ids, __hat__Profile_ids + 2, _s);
}

::std::vector< ::std::string>
hat::Profile::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__hat__Profile_ids[0], &__hat__Profile_ids[2]);
}

const ::std::string&
hat::Profile::ice_id(const ::Ice::Current&) const
{
    return __hat__Profile_ids[1];
}

const ::std::string&
hat::Profile::ice_staticId()
{
    return __hat__Profile_ids[1];
}

::Ice::DispatchStatus
hat::Profile::___refreshPath(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string path;
    ::hat::FileStatSeq fss;
    __is->read(path);
    ::hat::__readFileStatSeq(__is, fss);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::hat::FileStatSeq __ret = refreshPath(path, fss, __current);
    if(__ret.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        ::hat::__writeFileStatSeq(__os, &__ret[0], &__ret[0] + __ret.size());
    }
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
hat::Profile::___updateFile(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::hat::FileStat stat;
    ::std::string hash;
    stat.__read(__is);
    __is->read(hash);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    bool __ret = updateFile(stat, hash, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
hat::Profile::___updateMeta(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::hat::ImageMeta meta;
    meta.__read(__is);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    bool __ret = updateMeta(meta, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
hat::Profile::___updateFeature(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::hat::ImageFeature feature;
    feature.__read(__is);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    bool __ret = updateFeature(feature, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __hat__Profile_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "refreshPath",
    "updateFeature",
    "updateFile",
    "updateMeta"
};

::Ice::DispatchStatus
hat::Profile::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__hat__Profile_all, __hat__Profile_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __hat__Profile_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___refreshPath(in, current);
        }
        case 5:
        {
            return ___updateFeature(in, current);
        }
        case 6:
        {
            return ___updateFile(in, current);
        }
        case 7:
        {
            return ___updateMeta(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
hat::Profile::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
hat::Profile::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
hat::Profile::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type hat::Profile was not generated with stream support";
    throw ex;
}

void
hat::Profile::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type hat::Profile was not generated with stream support";
    throw ex;
}
#endif

void 
hat::__patch__ProfilePtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::hat::ProfilePtr* p = static_cast< ::hat::ProfilePtr*>(__addr);
    assert(p);
    *p = ::hat::ProfilePtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::hat::Profile::ice_staticId(), v->ice_id());
    }
}
