// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Synchronizer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __Synchronizer_h__
#define __Synchronizer_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/BuiltinSequences.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace hat
{

class Synchronizer;

}

}

namespace hat
{

class Synchronizer;
bool operator==(const Synchronizer&, const Synchronizer&);
bool operator<(const Synchronizer&, const Synchronizer&);

}

namespace IceInternal
{

::Ice::Object* upCast(::hat::Synchronizer*);
::IceProxy::Ice::Object* upCast(::IceProxy::hat::Synchronizer*);

}

namespace hat
{

typedef ::IceInternal::Handle< ::hat::Synchronizer> SynchronizerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::hat::Synchronizer> SynchronizerPrx;

void __read(::IceInternal::BasicStream*, SynchronizerPrx&);
void __patch__SynchronizerPtr(void*, ::Ice::ObjectPtr&);

}

namespace hat
{

class Callback_Synchronizer_refresh_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Synchronizer_refresh_Base> Callback_Synchronizer_refreshPtr;

}

namespace IceProxy
{

namespace hat
{

class Synchronizer : virtual public ::IceProxy::Ice::Object
{
public:

    void refresh(const ::std::string& path)
    {
        refresh(path, 0);
    }
    void refresh(const ::std::string& path, const ::Ice::Context& __ctx)
    {
        refresh(path, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path)
    {
        return begin_refresh(path, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path, const ::Ice::Context& __ctx)
    {
        return begin_refresh(path, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_refresh(path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_refresh(path, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path, const ::hat::Callback_Synchronizer_refreshPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_refresh(path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_refresh(const ::std::string& path, const ::Ice::Context& __ctx, const ::hat::Callback_Synchronizer_refreshPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_refresh(path, &__ctx, __del, __cookie);
    }

    void end_refresh(const ::Ice::AsyncResultPtr&);
    
private:

    void refresh(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_refresh(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Synchronizer> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Synchronizer*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Synchronizer*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace hat
{

class Synchronizer : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void refresh(const ::std::string&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace hat
{

class Synchronizer : virtual public ::IceDelegate::hat::Synchronizer,
                     virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void refresh(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace hat
{

class Synchronizer : virtual public ::IceDelegate::hat::Synchronizer,
                     virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void refresh(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace hat
{

class Synchronizer : virtual public ::Ice::Object
{
public:

    typedef SynchronizerPrx ProxyType;
    typedef SynchronizerPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void refresh(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___refresh(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const Synchronizer& l, const Synchronizer& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Synchronizer& l, const Synchronizer& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace hat
{

template<class T>
class CallbackNC_Synchronizer_refresh : public Callback_Synchronizer_refresh_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Synchronizer_refresh(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Synchronizer_refresh<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Synchronizer_refresh<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Synchronizer_refresh<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Synchronizer_refresh<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Synchronizer_refresh : public Callback_Synchronizer_refresh_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Synchronizer_refresh(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Synchronizer_refresh<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Synchronizer_refresh<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Synchronizer_refresh<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Synchronizer_refreshPtr
newCallback_Synchronizer_refresh(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Synchronizer_refresh<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
