// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Synchronizer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#include <Synchronizer.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __hat__Synchronizer__refresh_name = "refresh";

::Ice::Object* IceInternal::upCast(::hat::Synchronizer* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::hat::Synchronizer* p) { return p; }

void
hat::__read(::IceInternal::BasicStream* __is, ::hat::SynchronizerPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::hat::Synchronizer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::hat::Synchronizer::refresh(const ::std::string& path, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::hat::Synchronizer* __del = dynamic_cast< ::IceDelegate::hat::Synchronizer*>(__delBase.get());
            __del->refresh(path, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::hat::Synchronizer::begin_refresh(const ::std::string& path, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __hat__Synchronizer__refresh_name, __del, __cookie);
    try
    {
        __result->__prepare(__hat__Synchronizer__refresh_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(path);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::hat::Synchronizer::end_refresh(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __hat__Synchronizer__refresh_name);
}

const ::std::string&
IceProxy::hat::Synchronizer::ice_staticId()
{
    return ::hat::Synchronizer::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::hat::Synchronizer::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::hat::Synchronizer);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::hat::Synchronizer::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::hat::Synchronizer);
}

::IceProxy::Ice::Object*
IceProxy::hat::Synchronizer::__newInstance() const
{
    return new Synchronizer;
}

void
IceDelegateM::hat::Synchronizer::refresh(const ::std::string& path, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __hat__Synchronizer__refresh_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(path);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::hat::Synchronizer::refresh(const ::std::string& path, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& path, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_path(path)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::hat::Synchronizer* servant = dynamic_cast< ::hat::Synchronizer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->refresh(_m_path, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_path;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __hat__Synchronizer__refresh_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(path, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
hat::Synchronizer::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __hat__Synchronizer_ids[2] =
{
    "::Ice::Object",
    "::hat::Synchronizer"
};

bool
hat::Synchronizer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__hat__Synchronizer_ids, __hat__Synchronizer_ids + 2, _s);
}

::std::vector< ::std::string>
hat::Synchronizer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__hat__Synchronizer_ids[0], &__hat__Synchronizer_ids[2]);
}

const ::std::string&
hat::Synchronizer::ice_id(const ::Ice::Current&) const
{
    return __hat__Synchronizer_ids[1];
}

const ::std::string&
hat::Synchronizer::ice_staticId()
{
    return __hat__Synchronizer_ids[1];
}

::Ice::DispatchStatus
hat::Synchronizer::___refresh(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string path;
    __is->read(path);
    __is->endReadEncaps();
    refresh(path, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __hat__Synchronizer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "refresh"
};

::Ice::DispatchStatus
hat::Synchronizer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__hat__Synchronizer_all, __hat__Synchronizer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __hat__Synchronizer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___refresh(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
hat::Synchronizer::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
hat::Synchronizer::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
hat::Synchronizer::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type hat::Synchronizer was not generated with stream support";
    throw ex;
}

void
hat::Synchronizer::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type hat::Synchronizer was not generated with stream support";
    throw ex;
}
#endif

void 
hat::__patch__SynchronizerPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::hat::SynchronizerPtr* p = static_cast< ::hat::SynchronizerPtr*>(__addr);
    assert(p);
    *p = ::hat::SynchronizerPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::hat::Synchronizer::ice_staticId(), v->ice_id());
    }
}
