// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

// <auto-generated>
//
// Generated from file `Filter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>

#ifndef __Filter_h__
#define __Filter_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/BuiltinSequences.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace hat
{

class Filter;

}

}

namespace hat
{

class Filter;
bool operator==(const Filter&, const Filter&);
bool operator<(const Filter&, const Filter&);

}

namespace IceInternal
{

::Ice::Object* upCast(::hat::Filter*);
::IceProxy::Ice::Object* upCast(::IceProxy::hat::Filter*);

}

namespace hat
{

typedef ::IceInternal::Handle< ::hat::Filter> FilterPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::hat::Filter> FilterPrx;

void __read(::IceInternal::BasicStream*, FilterPrx&);
void __patch__FilterPtr(void*, ::Ice::ObjectPtr&);

}

namespace hat
{

struct FileInfo
{
    ::Ice::Int id;
    ::std::string uri;
    ::Ice::Long stamp;
    ::Ice::Long size;
    ::std::string hash;

    bool operator==(const FileInfo& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(id != __rhs.id)
        {
            return false;
        }
        if(uri != __rhs.uri)
        {
            return false;
        }
        if(stamp != __rhs.stamp)
        {
            return false;
        }
        if(size != __rhs.size)
        {
            return false;
        }
        if(hash != __rhs.hash)
        {
            return false;
        }
        return true;
    }

    bool operator<(const FileInfo& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(id < __rhs.id)
        {
            return true;
        }
        else if(__rhs.id < id)
        {
            return false;
        }
        if(uri < __rhs.uri)
        {
            return true;
        }
        else if(__rhs.uri < uri)
        {
            return false;
        }
        if(stamp < __rhs.stamp)
        {
            return true;
        }
        else if(__rhs.stamp < stamp)
        {
            return false;
        }
        if(size < __rhs.size)
        {
            return true;
        }
        else if(__rhs.size < size)
        {
            return false;
        }
        if(hash < __rhs.hash)
        {
            return true;
        }
        else if(__rhs.hash < hash)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const FileInfo& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const FileInfo& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const FileInfo& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const FileInfo& __rhs) const
    {
        return !operator<(__rhs);
    }

    void __write(::IceInternal::BasicStream*) const;
    void __read(::IceInternal::BasicStream*);
};

typedef ::std::vector< ::hat::FileInfo> FileInfoSeq;
void __writeFileInfoSeq(::IceInternal::BasicStream*, const ::hat::FileInfo*, const ::hat::FileInfo*);
void __readFileInfoSeq(::IceInternal::BasicStream*, FileInfoSeq&);

}

namespace hat
{

class Callback_Filter_select_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Filter_select_Base> Callback_Filter_selectPtr;

class Callback_Filter_score_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Filter_score_Base> Callback_Filter_scorePtr;

}

namespace IceProxy
{

namespace hat
{

class Filter : virtual public ::IceProxy::Ice::Object
{
public:

    ::hat::FileInfoSeq select(const ::std::string& where)
    {
        return select(where, 0);
    }
    ::hat::FileInfoSeq select(const ::std::string& where, const ::Ice::Context& __ctx)
    {
        return select(where, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where)
    {
        return begin_select(where, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where, const ::Ice::Context& __ctx)
    {
        return begin_select(where, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_select(where, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_select(where, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where, const ::hat::Callback_Filter_selectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_select(where, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_select(const ::std::string& where, const ::Ice::Context& __ctx, const ::hat::Callback_Filter_selectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_select(where, &__ctx, __del, __cookie);
    }

    ::hat::FileInfoSeq end_select(const ::Ice::AsyncResultPtr&);
    
private:

    ::hat::FileInfoSeq select(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_select(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::hat::FileInfoSeq score(::Ice::Int id)
    {
        return score(id, 0);
    }
    ::hat::FileInfoSeq score(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        return score(id, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id)
    {
        return begin_score(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        return begin_score(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_score(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_score(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id, const ::hat::Callback_Filter_scorePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_score(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_score(::Ice::Int id, const ::Ice::Context& __ctx, const ::hat::Callback_Filter_scorePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_score(id, &__ctx, __del, __cookie);
    }

    ::hat::FileInfoSeq end_score(const ::Ice::AsyncResultPtr&);
    
private:

    ::hat::FileInfoSeq score(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_score(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Filter> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Filter> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Filter*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Filter*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace hat
{

class Filter : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::hat::FileInfoSeq select(const ::std::string&, const ::Ice::Context*) = 0;

    virtual ::hat::FileInfoSeq score(::Ice::Int, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace hat
{

class Filter : virtual public ::IceDelegate::hat::Filter,
               virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::hat::FileInfoSeq select(const ::std::string&, const ::Ice::Context*);

    virtual ::hat::FileInfoSeq score(::Ice::Int, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace hat
{

class Filter : virtual public ::IceDelegate::hat::Filter,
               virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::hat::FileInfoSeq select(const ::std::string&, const ::Ice::Context*);

    virtual ::hat::FileInfoSeq score(::Ice::Int, const ::Ice::Context*);
};

}

}

namespace hat
{

class Filter : virtual public ::Ice::Object
{
public:

    typedef FilterPrx ProxyType;
    typedef FilterPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::hat::FileInfoSeq select(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___select(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::hat::FileInfoSeq score(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___score(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const Filter& l, const Filter& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Filter& l, const Filter& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace hat
{

template<class T>
class CallbackNC_Filter_select : public Callback_Filter_select_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::hat::FileInfoSeq&);

    CallbackNC_Filter_select(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::FilterPrx __proxy = ::hat::FilterPrx::uncheckedCast(__result->getProxy());
        ::hat::FileInfoSeq __ret;
        try
        {
            __ret = __proxy->end_select(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_Filter_selectPtr
newCallback_Filter_select(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::hat::FileInfoSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Filter_select<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Filter_selectPtr
newCallback_Filter_select(T* instance, void (T::*cb)(const ::hat::FileInfoSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Filter_select<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Filter_select : public Callback_Filter_select_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::hat::FileInfoSeq&, const CT&);

    Callback_Filter_select(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::FilterPrx __proxy = ::hat::FilterPrx::uncheckedCast(__result->getProxy());
        ::hat::FileInfoSeq __ret;
        try
        {
            __ret = __proxy->end_select(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Filter_selectPtr
newCallback_Filter_select(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::hat::FileInfoSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Filter_select<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Filter_selectPtr
newCallback_Filter_select(T* instance, void (T::*cb)(const ::hat::FileInfoSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Filter_select<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Filter_score : public Callback_Filter_score_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::hat::FileInfoSeq&);

    CallbackNC_Filter_score(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::FilterPrx __proxy = ::hat::FilterPrx::uncheckedCast(__result->getProxy());
        ::hat::FileInfoSeq __ret;
        try
        {
            __ret = __proxy->end_score(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_Filter_scorePtr
newCallback_Filter_score(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::hat::FileInfoSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Filter_score<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Filter_scorePtr
newCallback_Filter_score(T* instance, void (T::*cb)(const ::hat::FileInfoSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Filter_score<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Filter_score : public Callback_Filter_score_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::hat::FileInfoSeq&, const CT&);

    Callback_Filter_score(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::hat::FilterPrx __proxy = ::hat::FilterPrx::uncheckedCast(__result->getProxy());
        ::hat::FileInfoSeq __ret;
        try
        {
            __ret = __proxy->end_score(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Filter_scorePtr
newCallback_Filter_score(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::hat::FileInfoSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Filter_score<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Filter_scorePtr
newCallback_Filter_score(T* instance, void (T::*cb)(const ::hat::FileInfoSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Filter_score<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
